#!/usr/bin/env bash
# This script installs and configures Nginx server
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
