#!/usr/bin/env bash
# This script installs and configures Nginx server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;/" /etc/nginx/sites-available/default
service nginx start
