#!/usr/bin/env bash
# This script installs and configures Nginx server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.youtube.com permanent;\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
service nginx start
