#!/usr/bin/env bash
# Fix the symbolic link of nginx
sudo service nginx stop
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-availabe/default /etc/nginx/sites-enabled/default
sudo service nginx start