#!/usr/bin/env bash
# Fix the symbolic link of nginx
sudo service nginx stop; rm /etc/nginx/sites-enabled/default; ln -s /etc/nginx/sites-availabe/default /etc/nginx/sites-enabled/default; service nginx start
