#!/usr/bin/env bash
# Process and PID file
file=/var/run/holbertonscript.pid
trap "echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm $file; exit' SIGQUIT SIGTERM
echo $$ > "$file"
while true;
do
	echo To infinity and beyond
	sleep 2
done
