#!/usr/bin/env bash
# Read and cut passwd
filename='/etc/passwd'
while read -r line;
do
    echo -n "$line" | cut -d ':' -f 1 | tr -d '\n'
    echo ":" | tr -d '\n'
    echo -n "$line" | cut -d ':' -f 3 | tr -d '\n'
    echo ":" | tr -d '\n'
    echo -n "$line" | cut -d ':' -f 6
done < $filename
