#!/usr/bin/env bash
# Script that fixes the container and configures the nginx with a user nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
